image:
  - Visual Studio 2019
  
platform:
  - x64
  
configuration:
  - Release
  
before_build:
- cmd: cmake -H. -B./build -DCMAKE_INSTALL_PREFIX=./package -DYAML_CPP_BUILD_TOOLS="OFF" -DYAML_CPP_BUILD_TESTS="OFF"
  
build:
  publish_nuget: true
  verbosity: normal
  project: build/INSTALL.vcxproj
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production